SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM MEMBER_PROFILE AS m  JOIN REST_REVIEW AS r ON m.MEMBER_ID = r.MEMBER_ID
WHERE m.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY(MEMBER_ID) ORDER BY COUNT(REVIEW_ID) desc limit 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT